language: c
env:
  global:
    - GAP_PKGS_TO_BUILD="io profiling AttributeScheduler GAPDoc grape AutoDoc simplicial"
    - GAP_PKGS_TO_CLONE="sebasguts/AttributeScheduler.git sebasguts/NautyTracesInterface.git markusbaumeister/simplicial-surfaces.git"

addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - zlib1g-dev

matrix:
  include:
    - env: GAPBRANCH=master
    - env: GAPBRANCH=stable-4.9
    - env: GAPBRANCH=stable-4.10

branches:
  only:
    - master

before_script:
  - export GAPROOT="$HOME/gap"
  - git clone https://github.com/gap-system/pkg-ci-scripts.git scripts
  - scripts/build_gap.sh
  - $GAPROOT/pkg/NautyTracesInterface/install.sh --gaproot $GAPROOT

script:
  - scripts/build_pkg.sh && scripts/run_tests.sh && $GAPROOT/bin/gap.sh $GAPROOT/pkg/simplicial-surfaces/maketest.g

after_script:
  - bash scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
