language: c
env:
  global:
    - GAPROOT=gaproot
    - COVDIR=coverage
    - GAP_PKGS_TO_BUILD="AttributeScheduler GAPDoc grape AutoDoc simplicial"
    - GAP_PKGS_TO_CLONE="sebasguts/AttributeScheduler.git sebasguts/NautyTracesInterface.git markusbaumeister/simplicial-surfaces"
    - CODECOV_TOKEN="1ec2fabd-42cd-4aed-a479-462f345ae841"
    - GAP_TESTFILE="maketest.g"

addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev

matrix:
  include:
    - env: CFLAGS="-O2"

branches:
  only:
    - master

before_script:
  - export GAPROOT="$HOME/gap"
  - git clone https://github.com/gap-system/pkg-ci-scripts.git scripts
  - scripts/build_gap.sh
  - scripts/build_pkg.sh
  - ls
  - $GAPROOT/pkg/NautyTracesInterface/install.sh --gaproot $GAPROOT

script:
  - scripts/run_tests.sh

after_script:
  - bash scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
