language: c
env:
  global:
    - GAPROOT=gaproot
    - COVDIR=coverage
    - GAP_PKGS_TO_BUILD="GAPDoc grape AutoDoc"



addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev

matrix:
  include:
    - env: CFLAGS="-O2"

branches:
  only:
    - master

before_script:
  - export GAPROOT="$HOME/gap"
  - git clone https://github.com/gap-system/pkg-ci-scripts.git scripts
  - scripts/build_gap.sh
  - git clone https://github.com/markusbaumeister/simplicial-surfaces.git surfaces
  - ln -s surfaces gap/pkg/surfaces
  - git clone https://github.com/sebasguts/AttributeScheduler.git scheduler
  - ln -s scheduler gap/pkg/AttributeScheduler
  - cd scheduler
  - make
  - cd ..
  - git clone https://github.com/sebasguts/NautyTracesInterface.git nauty
  - ln -s nauty gap/pkg/Nauty
  - nauty/install.sh --gaproot GAPROOT

script:
  - scripts/build_pkg.sh
  - cd surfaces/
  - gap makedoc.g
  - gap maketest.g
after_script:
  - bash scripts/gather-coverage.sh
- bash <(curl -s https://codecov.io/bash)
